# apiVersion v2 is Helm 3
---
apiVersion: v2
name: face-api
version: 0.1.0
appVersion: "3.2.325.304"
description: Face Recognition Service
home: https://faceapi.regulaforensics.com/
sources:
  - https://github.com/regulaforensics/face-api-helm
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - face-api
  - regulaforensics
dependencies:
  - name: postgresql
    version: 10.5.3
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
annotations:
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.regulaforensics.com/develop/face-sdk/web-service/
