# apiVersion v2 is Helm 3
---
apiVersion: v2
name: api-gateway
version: 0.1.2
appVersion: api-gateway-2.2.5
description: ML. Airflow API Gateway
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - regulaforensics
  - api-gateway
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
