apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docreader.fullname" . }}
  labels: {{- include "docreader.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels: {{- include "docreader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels: {{- include "docreader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: docreader
              containerPort: 8080
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /api/ping
              port: docreader
              {{- if .Values.ssl.enabled }}
              scheme: HTTPS
              {{- else }}
              scheme: HTTP
              {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /api/readiness
              port: docreader
              {{- if .Values.ssl.enabled }}
              scheme: HTTPS
              {{- else }}
              scheme: HTTP
              {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- include "docreader.envs" . | indent 10 }}
            {{- if and (eq .Values.storage.type "s3") .Values.storage.s3.awsCredentialsSecretName }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "docreader.aws.credentials.secret" . }}
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "docreader.aws.credentials.secret" . }}
                  key: AWS_SECRET_ACCESS_KEY
            {{- end }}
            {{- if and (eq .Values.storage.type "az") .Values.storage.az.connectionStringSecretName }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ template "docreader.az.credentials.secret" . }}
                  key: AZURE_STORAGE_CONNECTION_STRING
            {{- end }}
            {{- if and (not .Values.postgresql.enabled) .Values.database.connectionStringSecretName }}
            - name: SQL_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ template "docreader.db.credentials.secret" . }}
                  key: SQL_CONNECTION_STRING
            {{- end }}
          volumeMounts:
            - name: docreader-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if .Values.licenseSecretName }}
            - name: license
              mountPath: /app/extBin/unix_x64/regula.license
              subPath: regula.license
              readOnly: true
            {{- end }}
            {{- if .Values.ssl.certificatesSecretName }}
            - name: certificates
              mountPath: /app/certs
              readOnly: true
            {{- end }}
            {{- if and (eq .Values.storage.type "fs") .Values.processing.results.enabled .Values.processing.results.persistence.enabled }}
            - name: results
              mountPath: /app/output
            {{- end }}
            {{- if and (eq .Values.storage.type "gcs") .Values.storage.gcs.gcsKeyJsonSecretName }}
            - name: gcs-credentials
              mountPath: /etc/credentials/gcs_key.json
              subPath: gcs_key.json
              readOnly: true
            {{- end }}
            {{- if and .Values.sdk.rfid.rfidPkdPa .Values.sdk.rfid.existingClaim }}
            - name: rfidpkd
              mountPath: /app/rfid_pkd
            {{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: docreader-config
          configMap:
            name: {{ include "docreader.config.name" . }}
        {{- if .Values.licenseSecretName }}
        - name: license
          secret:
            secretName: {{ template "docreader.license.secret" . }}
        {{- end }}
        {{- if .Values.ssl.certificatesSecretName }}
        - name: certificates
          secret:
            secretName: {{ template "docreader.certificates.secret" . }}
        {{- end }}
        {{- if and (eq .Values.storage.type "fs") .Values.processing.results.enabled .Values.processing.results.persistence.enabled }}
        - name: results
          persistentVolumeClaim:
            claimName: {{ template "results_volume_claim" . }}
        {{- end }}
        {{- if and (eq .Values.storage.type "gcs") .Values.storage.gcs.gcsKeyJsonSecretName }}
        - name: gcs-credentials
          secret:
            secretName: {{ template "docreader.gcs.credentials.secret" . }}
        {{- end }}
        {{- if and .Values.sdk.rfid.rfidPkdPa .Values.sdk.rfid.existingClaim }}
        - name: rfidpkd
          persistentVolumeClaim:
            claimName: {{ template "rfidpkd_volume_claim" . }}
        {{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
