{{- if and .Values.config.sdk.rfid.enabled (not .Values.config.sdk.rfid.pkdPaExistingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "docreader.rfid.pkd.pvc" . }}
  labels: {{- include "docreader.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
{{- end }}
