# apiVersion v2 is Helm 3
---
apiVersion: v2
name: afis-api
home: https://test-afisapi.regulaforensics.com/
version: 0.1.0
appVersion: nightly
description: Afis api service. On-premise and cloud integration
icon: https://secure.gravatar.com/avatar/71a5efd69d82e444129ad18f51224bbb.jpg
keywords:
  - regula
  - afis-api
  - regulaforensics
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
maintainers:
  - email: support@regulaforensics.com
    name: Regula Forensics Support
    url: https://support.regulaforensics.com
type: application
